version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rmq_broker
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management Plugin Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ./services/producer
      dockerfile: Dockerfile
    container_name: nest_producer
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      NODE_ENV: development
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: ./services/consumer
      dockerfile: Dockerfile
    container_name: nest_consumer
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      NODE_ENV: development
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    container_name: nest_notification
    ports:
      - "3003:3000"
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      NODE_ENV: development
    depends_on:
      rabbitmq:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NODE_ENV: production
    depends_on:
      rabbitmq:
        condition: service_healthy
      producer:
        condition: service_started
      consumer:
        condition: service_started
      notification:
        condition: service_started

volumes:
  rmq_data:
