import React from 'react'
import { Sparkles, CheckCircle, AlertTriangle, Layers, ChevronRight } from 'lucide-react'
import { TranslationDict } from '../translations'

interface DocDetailsProps {
  t: TranslationDict
  setActiveTab: (tab: 'playground' | 'code' | 'docs') => void
}

export function DocDetails({ t, setActiveTab }: DocDetailsProps) {
  return (
    <div className="space-y-8 text-left">
      {/* SIGNATURE CORAL CARD FOR HIGH-VOLTAGE ARCHITECTURE */}
      <div className="p-8 rounded-xl bg-[#aa2d00] text-white flex flex-col md:flex-row justify-between items-start md:items-center gap-6 shadow-md">
        <div className="space-y-2 max-w-2xl">
          <div className="inline-flex items-center space-x-1.5 bg-white/20 px-3 py-1 rounded-full text-xs font-bold tracking-wide">
            <Sparkles className="w-4.5 h-4.5" />
            <span>SOLID & SOLID-Clean Principles Architecture</span>
          </div>
          <h2 className="text-3xl font-semibold tracking-tight">Microservices Architecture Manifesto</h2>
          <p className="text-white/80 text-sm leading-relaxed">
            We decouple our services following single responsibilities. The <strong>Producer Service</strong> does not share data structures, file layers, or memory space with the{' '}
            <strong>Consumer</strong>; they synchronize entirely through standard AMQP streams. This creates zero point bottlenecks, massive horizontal scaling options, and robust error fallback.
          </p>
        </div>
        <button onClick={() => setActiveTab('code')} className="px-6 py-3 bg-white text-[#aa2d00] hover:bg-gray-100 font-bold rounded-lg text-sm transition-colors whitespace-nowrap outline-hidden">
          Inspect Files Tree
        </button>
      </div>

      {/* DETAILED INFO GRIDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 pt-4">
        <div className="bg-[#0D111A] border border-slate-800 rounded-xl p-6 space-y-4 shadow-xl">
          <h3 className="text-lg font-semibold flex items-center space-x-2 text-white">
            <CheckCircle className="w-5 h-5 text-emerald-400" />
            <span>Idempotency Mechanisms</span>
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed">In distributed systems, networks can drop, duplicate, or re-deliver packets. Our architecture guarantees idempotency:</p>
          <ul className="space-y-2 text-xs text-slate-300 leading-relaxed font-normal">
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>Every ingested event triggers a unique UUID generated by the Producer.</span>
            </li>
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>The database or Consumer caches these transaction signatures during processing.</span>
            </li>
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>Duplicate packages arriving with active matching GUID tokens are automatically skipped or served from cache, preventing duplicate alerts to the customer.</span>
            </li>
          </ul>
        </div>

        <div className="bg-[#0D111A] border border-slate-800 rounded-xl p-6 space-y-4 shadow-xl font-sans">
          <h3 className="text-lg font-semibold flex items-center space-x-2 text-white">
            <AlertTriangle className="w-5 h-5 text-amber-500" />
            <span>Broker Error Recovery & Requeuing</span>
          </h3>
          <p className="text-xs text-slate-300 leading-relaxed">What happens when third-party servers (like Telegram Bot endpoints) collapse temporarily?</p>
          <ul className="space-y-2 text-xs text-slate-300 leading-relaxed font-normal">
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>
                With <strong>noAck: false</strong>, RabbitMQ preserves the message until the Consumer sends an explicit <code>ack</code> code.
              </span>
            </li>
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>
                If operations fail, we issue a <code>nack</code> with <code>requeue: true</code>, putting the message back to try again later.
              </span>
            </li>
            <li className="flex items-start">
              <ChevronRight className="w-4 h-4 text-[#fcab79] shrink-0 mt-0.5" />
              <span>
                After 3 retry failures, we discard or direct messages to a <strong>Dead-Letter Queue (DLX)</strong> for operator debugging and diagnostics, keeping queues clean.
              </span>
            </li>
          </ul>
        </div>
      </div>

      {/* DOCKER COMPOSE CONFIG GUIDE */}
      <div className="bg-[#0D111A] border border-slate-800 rounded-xl p-6 space-y-4 shadow-xl">
        <h3 className="text-lg font-semibold flex items-center space-x-2 text-white">
          <Layers className="w-5 h-5 text-[#fcab79]" />
          <span>Docker-Compose Deployment Guide</span>
        </h3>
        <p className="text-sm text-slate-300">We use Docker Compose to bind all microservices and dependency networks under a single operational environment. To launch the whole project locally:</p>

        <div className="bg-[#05060A]/95 border border-slate-800/80 rounded-lg p-4 font-mono text-xs space-y-2 text-slate-300 leading-normal">
          <p className="text-[#fcab79] font-bold"># Step 1: Clone the workspace</p>
          <p>git clone https://github.com/your-username/nest-rmq-telegram.git</p>
          <p>cd nest-rmq-telegram</p>
          <br />
          <p className="text-[#fcab79] font-bold"># Step 2: Configure secrets inside an .env file</p>
          <p>echo "TELEGRAM_BOT_TOKEN='your_token'" &gt; .env</p>
          <p>echo "TELEGRAM_CHAT_ID='your_chat_id'" &gt;&gt; .env</p>
          <br />
          <p className="text-[#fcab79] font-bold"># Step 3: Run compose or Makefile shortcuts</p>
          <p>make up</p>
          <br />
          <p className="text-emerald-400 font-bold"># Verified: Docker-Compose will compile images and launch RabbitMQ + 3 services!</p>
        </div>
      </div>
    </div>
  )
}
